-- =============================================================================
-- TEHILA BODYSHOP CRM — FRESH PROJECT SETUP
-- Generated by concatenating migrations/001–019 in order.
-- Run this ONCE in a new Supabase project's SQL Editor.
--
-- Prerequisites BEFORE running:
--   1. In Supabase Dashboard → Storage → create buckets (private):
--        - extras-images
--        - painter-images
--        - case-documents
--   2. Paste this file in SQL Editor → Run.
-- =============================================================================


-- =============================================================================
-- 001_init.sql
-- =============================================================================
-- =====================================================
-- Tehila Bodyshop CRM - Initial Schema
-- Migration: 001_init.sql
-- =====================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- ENUMS
-- =====================================================

CREATE TYPE user_role AS ENUM (
  'SERVICE_MANAGER',
  'OFFICE',
  'CEO',
  'PAINTER',
  'SERVICE_ADVISOR'
);

CREATE TYPE general_status AS ENUM (
  'NEW',
  'IN_PROGRESS',
  'COMPLETED'
);

CREATE TYPE parts_status AS ENUM (
  'NO_PARTS',
  'ORDERED',
  'AVAILABLE'
);

CREATE TYPE insurance_type AS ENUM (
  'COMPREHENSIVE',
  'THIRD_PARTY',
  'PRIVATE',
  'OTHER'
);

CREATE TYPE claim_type AS ENUM (
  'PRIVATE',
  'ACCIDENT',
  'FLOOD'
);

CREATE TYPE workflow_type AS ENUM (
  'PROFESSIONAL',
  'CLOSURE'
);

CREATE TYPE workflow_run_status AS ENUM (
  'ACTIVE',
  'COMPLETED'
);

CREATE TYPE step_state AS ENUM (
  'PENDING',
  'ACTIVE',
  'DONE',
  'SKIPPED'
);

CREATE TYPE approval_type AS ENUM (
  'ESTIMATE_AND_DETAILS',
  'WHEELS_CHECK'
);

CREATE TYPE approval_status AS ENUM (
  'PENDING',
  'APPROVED',
  'REJECTED'
);

CREATE TYPE extra_status AS ENUM (
  'IN_TREATMENT',
  'REJECTED',
  'DONE'
);

CREATE TYPE audit_entity_type AS ENUM (
  'CASE',
  'WORKFLOW_STEP',
  'APPROVAL',
  'EXTRA'
);

-- =====================================================
-- TABLES
-- =====================================================

CREATE TABLE branches (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  role user_role NOT NULL,
  branch_id UUID REFERENCES branches(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE cars (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  license_plate TEXT,
  make TEXT,
  model TEXT,
  year INTEGER,
  vin TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE cases (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  car_id UUID NOT NULL REFERENCES cars(id) ON DELETE RESTRICT,
  general_status general_status NOT NULL DEFAULT 'NEW',
  parts_status parts_status NOT NULL DEFAULT 'NO_PARTS',
  insurance_type insurance_type,
  claim_type claim_type,
  fixcar_link TEXT,
  closed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE case_workflow_runs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  workflow_type workflow_type NOT NULL,
  status workflow_run_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE case_workflow_steps (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  run_id UUID NOT NULL REFERENCES case_workflow_runs(id) ON DELETE CASCADE,
  step_key TEXT NOT NULL,
  state step_state NOT NULL DEFAULT 'PENDING',
  order_index INTEGER NOT NULL,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ceo_approvals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  approval_type approval_type NOT NULL,
  status approval_status NOT NULL DEFAULT 'PENDING',
  rejection_note TEXT,
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bodywork_extras (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  image_path TEXT NOT NULL,
  status extra_status NOT NULL DEFAULT 'IN_TREATMENT',
  created_by UUID NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT,
  read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE audit_events (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  entity_type audit_entity_type NOT NULL,
  entity_id UUID NOT NULL,
  action TEXT NOT NULL,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  payload JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================
-- INDEXES
-- =====================================================

CREATE INDEX idx_profiles_branch_id ON profiles(branch_id);
CREATE INDEX idx_profiles_role ON profiles(role);
CREATE INDEX idx_cars_branch_id ON cars(branch_id);
CREATE INDEX idx_cars_license_plate ON cars(license_plate);
CREATE INDEX idx_cases_branch_id ON cases(branch_id);
CREATE INDEX idx_cases_car_id ON cases(car_id);
CREATE INDEX idx_cases_general_status ON cases(general_status);
CREATE INDEX idx_cases_closed_at ON cases(closed_at) WHERE closed_at IS NULL;
CREATE INDEX idx_case_workflow_runs_case_id ON case_workflow_runs(case_id);
CREATE INDEX idx_case_workflow_runs_status ON case_workflow_runs(status);
CREATE INDEX idx_case_workflow_steps_run_id ON case_workflow_steps(run_id);
CREATE INDEX idx_case_workflow_steps_step_key ON case_workflow_steps(step_key);
CREATE INDEX idx_ceo_approvals_case_id ON ceo_approvals(case_id);
CREATE INDEX idx_ceo_approvals_status ON ceo_approvals(status);
CREATE INDEX idx_bodywork_extras_case_id ON bodywork_extras(case_id);
CREATE INDEX idx_bodywork_extras_status ON bodywork_extras(status);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_read ON notifications(user_id, read);
CREATE INDEX idx_audit_events_entity ON audit_events(entity_type, entity_id);
CREATE INDEX idx_audit_events_created_at ON audit_events(created_at);

-- =====================================================
-- RLS
-- =====================================================

ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE cars ENABLE ROW LEVEL SECURITY;
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_workflow_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_workflow_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE ceo_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE bodywork_extras ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;

-- Helper: get current user's profile (branch_id, role)
CREATE OR REPLACE FUNCTION public.user_profile()
RETURNS TABLE (profile_id UUID, branch_id UUID, role user_role) AS $$
  SELECT id, profiles.branch_id, profiles.role
  FROM profiles
  WHERE id = auth.uid();
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- Branches: authenticated users can read branches (for their context)
CREATE POLICY branches_select ON branches
  FOR SELECT TO authenticated USING (true);

-- Profiles: users can read own profile; read others in same branch for workflow
CREATE POLICY profiles_select_own ON profiles
  FOR SELECT TO authenticated USING (id = auth.uid());

CREATE POLICY profiles_select_branch ON profiles
  FOR SELECT TO authenticated
  USING (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
  );

CREATE POLICY profiles_update_own ON profiles
  FOR UPDATE TO authenticated USING (id = auth.uid());

-- Cars: branch-scoped
CREATE POLICY cars_select ON cars
  FOR SELECT TO authenticated
  USING (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
  );

CREATE POLICY cars_insert ON cars
  FOR INSERT TO authenticated
  WITH CHECK (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
  );

CREATE POLICY cars_update ON cars
  FOR UPDATE TO authenticated
  USING (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
  );

-- Cases: branch-scoped
CREATE POLICY cases_select ON cases
  FOR SELECT TO authenticated
  USING (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
  );

CREATE POLICY cases_insert ON cases
  FOR INSERT TO authenticated
  WITH CHECK (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
  );

CREATE POLICY cases_update ON cases
  FOR UPDATE TO authenticated
  USING (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
  );

-- Case workflow runs: via case branch
CREATE POLICY case_workflow_runs_select ON case_workflow_runs
  FOR SELECT TO authenticated
  USING (
    case_id IN (
      SELECT id FROM cases WHERE branch_id IN (
        SELECT branch_id FROM profiles WHERE id = auth.uid()
      )
    )
  );

CREATE POLICY case_workflow_runs_insert ON case_workflow_runs
  FOR INSERT TO authenticated
  WITH CHECK (
    case_id IN (
      SELECT id FROM cases WHERE branch_id IN (
        SELECT branch_id FROM profiles WHERE id = auth.uid()
      )
    )
  );

CREATE POLICY case_workflow_runs_update ON case_workflow_runs
  FOR UPDATE TO authenticated
  USING (
    case_id IN (
      SELECT id FROM cases WHERE branch_id IN (
        SELECT branch_id FROM profiles WHERE id = auth.uid()
      )
    )
  );

-- Case workflow steps: via run -> case -> branch
CREATE POLICY case_workflow_steps_select ON case_workflow_steps
  FOR SELECT TO authenticated
  USING (
    run_id IN (
      SELECT cwr.id FROM case_workflow_runs cwr
      JOIN cases c ON c.id = cwr.case_id
      WHERE c.branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    )
  );

CREATE POLICY case_workflow_steps_insert ON case_workflow_steps
  FOR INSERT TO authenticated
  WITH CHECK (
    run_id IN (
      SELECT cwr.id FROM case_workflow_runs cwr
      JOIN cases c ON c.id = cwr.case_id
      WHERE c.branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    )
  );

CREATE POLICY case_workflow_steps_update ON case_workflow_steps
  FOR UPDATE TO authenticated
  USING (
    run_id IN (
      SELECT cwr.id FROM case_workflow_runs cwr
      JOIN cases c ON c.id = cwr.case_id
      WHERE c.branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    )
  );

-- CEO approvals: CEO can manage; others read by branch
CREATE POLICY ceo_approvals_select ON ceo_approvals
  FOR SELECT TO authenticated
  USING (
    case_id IN (
      SELECT id FROM cases WHERE branch_id IN (
        SELECT branch_id FROM profiles WHERE id = auth.uid()
      )
    )
  );

CREATE POLICY ceo_approvals_insert ON ceo_approvals
  FOR INSERT TO authenticated
  WITH CHECK (
    case_id IN (
      SELECT id FROM cases WHERE branch_id IN (
        SELECT branch_id FROM profiles WHERE id = auth.uid()
      )
    )
  );

CREATE POLICY ceo_approvals_update ON ceo_approvals
  FOR UPDATE TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
    OR case_id IN (
      SELECT id FROM cases WHERE branch_id IN (
        SELECT branch_id FROM profiles WHERE id = auth.uid()
      )
    )
  );

-- Bodywork extras: branch via case; PAINTER can insert, SERVICE_MANAGER can update status
CREATE POLICY bodywork_extras_select ON bodywork_extras
  FOR SELECT TO authenticated
  USING (
    case_id IN (
      SELECT id FROM cases WHERE branch_id IN (
        SELECT branch_id FROM profiles WHERE id = auth.uid()
      )
    )
  );

CREATE POLICY bodywork_extras_insert ON bodywork_extras
  FOR INSERT TO authenticated
  WITH CHECK (
    case_id IN (
      SELECT id FROM cases WHERE branch_id IN (
        SELECT branch_id FROM profiles WHERE id = auth.uid()
      )
    )
    AND created_by = auth.uid()
  );

CREATE POLICY bodywork_extras_update ON bodywork_extras
  FOR UPDATE TO authenticated
  USING (
    case_id IN (
      SELECT id FROM cases WHERE branch_id IN (
        SELECT branch_id FROM profiles WHERE id = auth.uid()
      )
    )
  );

-- Notifications: own only
CREATE POLICY notifications_select ON notifications
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY notifications_insert ON notifications
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY notifications_update ON notifications
  FOR UPDATE TO authenticated USING (user_id = auth.uid());

-- Audit events: branch-scoped read (entity_id may be case_id, etc.); insert for all authenticated
CREATE POLICY audit_events_select ON audit_events
  FOR SELECT TO authenticated
  USING (
    (entity_type = 'CASE' AND entity_id IN (SELECT id FROM cases WHERE branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())))
    OR (entity_type = 'WORKFLOW_STEP' AND entity_id IN (SELECT cws.id FROM case_workflow_steps cws JOIN case_workflow_runs cwr ON cwr.id = cws.run_id JOIN cases c ON c.id = cwr.case_id WHERE c.branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())))
    OR (entity_type = 'APPROVAL' AND entity_id IN (SELECT id FROM ceo_approvals WHERE case_id IN (SELECT id FROM cases WHERE branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid()))))
    OR (entity_type = 'EXTRA' AND entity_id IN (SELECT id FROM bodywork_extras WHERE case_id IN (SELECT id FROM cases WHERE branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid()))))
  );

CREATE POLICY audit_events_insert ON audit_events
  FOR INSERT TO authenticated WITH CHECK (true);

-- =====================================================
-- STORAGE: extras-images bucket (create via API/dashboard; policy here)
-- Run after creating bucket named 'extras-images' in Supabase Dashboard
-- =====================================================
-- Storage policies are typically added via Supabase Dashboard or separate migration.
-- Example policy for authenticated upload/read for extras-images:
-- INSERT INTO storage.buckets (id, name, public) VALUES ('extras-images', 'extras-images', false);
-- CREATE POLICY "extras-images upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'extras-images');
-- CREATE POLICY "extras-images read" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'extras-images');

-- =====================================================
-- UPDATED_AT TRIGGERS
-- =====================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER branches_updated_at BEFORE UPDATE ON branches
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER cars_updated_at BEFORE UPDATE ON cars
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER cases_updated_at BEFORE UPDATE ON cases
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER case_workflow_runs_updated_at BEFORE UPDATE ON case_workflow_runs
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER case_workflow_steps_updated_at BEFORE UPDATE ON case_workflow_steps
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER ceo_approvals_updated_at BEFORE UPDATE ON ceo_approvals
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER bodywork_extras_updated_at BEFORE UPDATE ON bodywork_extras
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- =============================================================================
-- 002_storage.sql
-- =============================================================================
-- =====================================================
-- Tehila Bodyshop CRM - Storage policies for extras-images
-- Migration: 002_storage.sql
-- Create bucket "extras-images" in Supabase Dashboard (Storage) first,
-- then run this migration to add RLS policies.
-- =====================================================

-- Policies for bucket: extras-images (must exist)
CREATE POLICY "extras-images authenticated upload"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'extras-images');

CREATE POLICY "extras-images authenticated read"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'extras-images');


-- =============================================================================
-- 003_schema_align.sql
-- =============================================================================
-- =====================================================
-- Tehila Bodyshop CRM - Schema alignment with plan
-- Migration: 003_schema_align.sql
-- Run after 001_init.sql
-- =====================================================

-- Cars: add first_registration_date (תאריך עלייה לכביש)
ALTER TABLE cars
  ADD COLUMN IF NOT EXISTS first_registration_date DATE;

-- Cases: add case_key, opened_at, treatment_finished_at, claim_number
ALTER TABLE cases
  ADD COLUMN IF NOT EXISTS case_key TEXT,
  ADD COLUMN IF NOT EXISTS opened_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS treatment_finished_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS claim_number TEXT;

-- Backfill opened_at from created_at for existing rows
UPDATE cases SET opened_at = created_at WHERE opened_at IS NULL;

-- Optional: unique index on case_key per branch to avoid duplicates
CREATE UNIQUE INDEX IF NOT EXISTS idx_cases_case_key_branch
  ON cases(branch_id, case_key) WHERE case_key IS NOT NULL;

-- Case workflow steps: who completed the step (for audit)
ALTER TABLE case_workflow_steps
  ADD COLUMN IF NOT EXISTS completed_by UUID REFERENCES profiles(id) ON DELETE SET NULL;

-- CEO approvals: who decided (for audit)
ALTER TABLE ceo_approvals
  ADD COLUMN IF NOT EXISTS decided_by UUID REFERENCES profiles(id) ON DELETE SET NULL;

-- =====================================================
-- RLS: CEO sees all (global visibility)
-- =====================================================

-- Cars: CEO can select all
CREATE POLICY cars_select_ceo ON cars
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO'));

-- Cases: CEO can select all
CREATE POLICY cases_select_ceo ON cases
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO'));

-- Case workflow runs: CEO can select all (via case)
CREATE POLICY case_workflow_runs_select_ceo ON case_workflow_runs
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO'));

-- Case workflow steps: CEO can select all
CREATE POLICY case_workflow_steps_select_ceo ON case_workflow_steps
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO'));

-- CEO approvals: CEO can select all
CREATE POLICY ceo_approvals_select_ceo ON ceo_approvals
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO'));

-- Bodywork extras: CEO can select all (via case)
CREATE POLICY bodywork_extras_select_ceo ON bodywork_extras
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO'));

-- Audit events: CEO can select all (broad read for oversight)
CREATE POLICY audit_events_select_ceo ON audit_events
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO'));


-- =============================================================================
-- 004_seed_branches.sql
-- =============================================================================
-- =====================================================
-- Tehila Bodyshop CRM - Seed branches
-- Migration: 004_seed_branches.sql
-- Run after 001_init.sql (and 003 if used)
-- =====================================================

INSERT INTO branches (name)
SELECT name FROM (VALUES ('NETIVOT'), ('ASHKELON')) AS t(name)
WHERE NOT EXISTS (SELECT 1 FROM branches b WHERE b.name = t.name);


-- =============================================================================
-- 005_case_documents.sql
-- =============================================================================
-- =====================================================
-- Tehila Bodyshop CRM - Case Documents
-- Migration: 005_case_documents.sql
-- =====================================================

-- Create case_documents table
CREATE TABLE IF NOT EXISTS case_documents (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL, -- Storage path in case-documents bucket
  file_size BIGINT, -- Size in bytes
  mime_type TEXT,
  uploaded_by UUID REFERENCES profiles(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_case_documents_case_id ON case_documents(case_id);
CREATE INDEX IF NOT EXISTS idx_case_documents_created_at ON case_documents(created_at DESC);

-- RLS Policies
ALTER TABLE case_documents ENABLE ROW LEVEL SECURITY;

-- Users can read documents for cases in their branch (or CEO can read all)
CREATE POLICY case_documents_select ON case_documents
  FOR SELECT TO authenticated
  USING (
    case_id IN (
      SELECT id FROM cases 
      WHERE branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
      OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
    )
  );

-- Users can upload documents for cases in their branch
CREATE POLICY case_documents_insert ON case_documents
  FOR INSERT TO authenticated
  WITH CHECK (
    case_id IN (
      SELECT id FROM cases 
      WHERE branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
      OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
    )
    AND uploaded_by = auth.uid()
  );

-- Users can delete their own documents or SERVICE_MANAGER/OFFICE can delete any in their branch
CREATE POLICY case_documents_delete ON case_documents
  FOR DELETE TO authenticated
  USING (
    uploaded_by = auth.uid()
    OR (
      case_id IN (
        SELECT id FROM cases 
        WHERE branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
      )
      AND EXISTS (
        SELECT 1 FROM profiles 
        WHERE id = auth.uid() 
        AND role IN ('SERVICE_MANAGER', 'OFFICE', 'CEO')
      )
    )
  );

-- Updated_at trigger
CREATE TRIGGER case_documents_updated_at
  BEFORE UPDATE ON case_documents
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- =====================================================
-- STORAGE: case-documents bucket
-- Create bucket "case-documents" in Supabase Dashboard (Storage) first,
-- then run the storage policies below.
-- =====================================================

-- Storage policies (run after creating bucket in Dashboard)
-- CREATE POLICY "case-documents authenticated upload"
-- ON storage.objects FOR INSERT TO authenticated
-- WITH CHECK (bucket_id = 'case-documents');

-- CREATE POLICY "case-documents authenticated read"
-- ON storage.objects FOR SELECT TO authenticated
-- USING (bucket_id = 'case-documents');

-- CREATE POLICY "case-documents authenticated delete"
-- ON storage.objects FOR DELETE TO authenticated
-- USING (bucket_id = 'case-documents');


-- =============================================================================
-- 005_verification_gaps.sql
-- =============================================================================
-- =====================================================
-- Tehila Bodyshop CRM - Verification plan gaps
-- Migration: 005_verification_gaps.sql
-- Run after 003_schema_align.sql
-- =====================================================

-- 1. profiles.is_active (for disabling users)
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;

-- 2. cases.created_by (audit: who opened the case)
ALTER TABLE cases
  ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES profiles(id) ON DELETE SET NULL;

-- 3. notifications.type (for filtering by category)
ALTER TABLE notifications
  ADD COLUMN IF NOT EXISTS type TEXT;

CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications(user_id, type);

-- 4. case_workflow_steps.activated_at (when step became ACTIVE, for SLA/reports)
ALTER TABLE case_workflow_steps
  ADD COLUMN IF NOT EXISTS activated_at TIMESTAMPTZ;


-- =============================================================================
-- 006_new_case_fields.sql
-- =============================================================================
-- Migration 006: New case fields + sub_claim_type enum + wheels_check_link + vehicle_type

-- Create sub_claim_type enum
CREATE TYPE sub_claim_type AS ENUM (
  'POLICY',
  'THIRD_PARTY',
  'THIRD_PARTY_SETTLEMENT',
  'PRIVATE_REPAIR',
  'SHLOMO_POLICY',
  'SHLOMO_THIRD_PARTY'
);

-- Add new fields to cases table
ALTER TABLE cases
  ADD COLUMN IF NOT EXISTS customer_name     TEXT,
  ADD COLUMN IF NOT EXISTS phone             TEXT,
  ADD COLUMN IF NOT EXISTS insurance_company TEXT,
  ADD COLUMN IF NOT EXISTS appraiser_name    TEXT,
  ADD COLUMN IF NOT EXISTS event_date        DATE,
  ADD COLUMN IF NOT EXISTS wheels_check_link TEXT,
  ADD COLUMN IF NOT EXISTS sub_claim_type    sub_claim_type;

-- Add vehicle_type to cars table
ALTER TABLE cars
  ADD COLUMN IF NOT EXISTS vehicle_type TEXT;


-- =============================================================================
-- 007_new_parts_status.sql
-- =============================================================================
-- Migration 007: Add AIRMAIL_PENDING to parts_status enum
-- Note: ALTER TYPE ADD VALUE cannot run inside a transaction block.
-- Run this migration separately, not inside BEGIN/COMMIT.

ALTER TYPE parts_status ADD VALUE IF NOT EXISTS 'AIRMAIL_PENDING';


-- =============================================================================
-- 008_workflow_steps_update.sql
-- =============================================================================
-- Migration 008: Update workflow steps for active cases
-- Removes SUMMARIZE_ESTIMATE, adds 3 new steps (ISSUE_CATALOG_NUMBERS, PARTS_DISCOUNTS, SEND_COMPLETION_PHOTOS)
-- Re-orders steps to match new workflow

-- Step 1: Remove SUMMARIZE_ESTIMATE steps entirely
DELETE FROM case_workflow_steps WHERE step_key = 'SUMMARIZE_ESTIMATE';

-- Step 2: Shift affected steps up by +100 to avoid index conflicts during migration
UPDATE case_workflow_steps
SET order_index = order_index + 100
WHERE step_key IN ('SEND_TO_APPRAISER', 'WAIT_APPRAISER_APPROVAL', 'ENTER_WORK', 'QUALITY_CONTROL', 'WASH', 'READY_FOR_OFFICE');

-- Step 3: Set final order_index values for all professional workflow steps
UPDATE case_workflow_steps SET order_index = 0 WHERE step_key = 'OPEN_CASE';
UPDATE case_workflow_steps SET order_index = 1 WHERE step_key = 'FIXCAR_PHOTOS';
UPDATE case_workflow_steps SET order_index = 2 WHERE step_key = 'WHEELS_CHECK';
UPDATE case_workflow_steps SET order_index = 3 WHERE step_key = 'PREP_ESTIMATE';
UPDATE case_workflow_steps SET order_index = 4 WHERE step_key = 'SEND_TO_APPRAISER';
UPDATE case_workflow_steps SET order_index = 5 WHERE step_key = 'WAIT_APPRAISER_APPROVAL';
UPDATE case_workflow_steps SET order_index = 6 WHERE step_key = 'ENTER_WORK';
UPDATE case_workflow_steps SET order_index = 9 WHERE step_key = 'QUALITY_CONTROL';
UPDATE case_workflow_steps SET order_index = 10 WHERE step_key = 'WASH';
UPDATE case_workflow_steps SET order_index = 12 WHERE step_key = 'READY_FOR_OFFICE';

-- Step 4: Insert new steps (ISSUE_CATALOG_NUMBERS) for active professional runs
INSERT INTO case_workflow_steps (run_id, step_key, state, order_index)
SELECT r.id, 'ISSUE_CATALOG_NUMBERS', 'PENDING', 7
FROM case_workflow_runs r
WHERE r.status = 'ACTIVE' AND r.workflow_type = 'PROFESSIONAL'
  AND NOT EXISTS (
    SELECT 1 FROM case_workflow_steps cs
    WHERE cs.run_id = r.id AND cs.step_key = 'ISSUE_CATALOG_NUMBERS'
  );

-- Step 5: Insert new steps (PARTS_DISCOUNTS)
INSERT INTO case_workflow_steps (run_id, step_key, state, order_index)
SELECT r.id, 'PARTS_DISCOUNTS', 'PENDING', 8
FROM case_workflow_runs r
WHERE r.status = 'ACTIVE' AND r.workflow_type = 'PROFESSIONAL'
  AND NOT EXISTS (
    SELECT 1 FROM case_workflow_steps cs
    WHERE cs.run_id = r.id AND cs.step_key = 'PARTS_DISCOUNTS'
  );

-- Step 6: Insert new steps (SEND_COMPLETION_PHOTOS)
INSERT INTO case_workflow_steps (run_id, step_key, state, order_index)
SELECT r.id, 'SEND_COMPLETION_PHOTOS', 'PENDING', 11
FROM case_workflow_runs r
WHERE r.status = 'ACTIVE' AND r.workflow_type = 'PROFESSIONAL'
  AND NOT EXISTS (
    SELECT 1 FROM case_workflow_steps cs
    WHERE cs.run_id = r.id AND cs.step_key = 'SEND_COMPLETION_PHOTOS'
  );


-- =============================================================================
-- 009_settings_tables.sql
-- =============================================================================
-- Migration 009: Settings tables (role_permissions + workflow_step_templates)

-- Role permissions table
CREATE TABLE IF NOT EXISTS role_permissions (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  role       TEXT NOT NULL,
  action     TEXT NOT NULL,
  enabled    BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(role, action)
);

-- Workflow step templates table (drives which steps are created for new cases)
CREATE TABLE IF NOT EXISTS workflow_step_templates (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  step_key             TEXT UNIQUE NOT NULL,
  step_label           TEXT NOT NULL,
  order_index          INTEGER NOT NULL,
  is_enabled           BOOLEAN NOT NULL DEFAULT true,
  requires_link        BOOLEAN NOT NULL DEFAULT false,
  requires_file_or_link BOOLEAN NOT NULL DEFAULT false,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed workflow_step_templates with the new step configuration
INSERT INTO workflow_step_templates (step_key, step_label, order_index, is_enabled, requires_link, requires_file_or_link) VALUES
  ('OPEN_CASE',               'פתיחת תיק',                          0,  true,  false, false),
  ('FIXCAR_PHOTOS',           'צילום FixCar',                        1,  true,  true,  false),
  ('WHEELS_CHECK',            'טפסי גלגלים',                         2,  true,  false, true),
  ('PREP_ESTIMATE',           'אומדן',                               3,  true,  false, false),
  ('SEND_TO_APPRAISER',       'שליחה לשמאי',                         4,  true,  false, false),
  ('WAIT_APPRAISER_APPROVAL', 'המתנה לאישור שמאי',                   5,  true,  false, false),
  ('ENTER_WORK',              'כניסה לעבודה',                        6,  true,  false, false),
  ('ISSUE_CATALOG_NUMBERS',   'ניפוק מק"טים',                        7,  true,  false, false),
  ('PARTS_DISCOUNTS',         'הנחות חלקים',                         8,  true,  false, false),
  ('QUALITY_CONTROL',         'בקרת איכות',                          9,  true,  false, false),
  ('WASH',                    'שטיפה',                               10, true,  false, false),
  ('SEND_COMPLETION_PHOTOS',  'שליחת תמונות לשמאי גמר תיקון',       11, true,  false, false),
  ('READY_FOR_OFFICE',        'מוכן למשרד',                          12, true,  false, false)
ON CONFLICT (step_key) DO NOTHING;

-- Seed role_permissions with default permissions
INSERT INTO role_permissions (role, action, enabled) VALUES
  ('SERVICE_MANAGER', 'create_case',              true),
  ('SERVICE_MANAGER', 'complete_professional_step', true),
  ('SERVICE_MANAGER', 'complete_closure_step',    false),
  ('SERVICE_MANAGER', 'manage_settings',          false),
  ('SERVICE_MANAGER', 'decide_approvals',         false),
  ('SERVICE_MANAGER', 'manage_extras_status',     true),
  ('SERVICE_MANAGER', 'upload_documents',         true),
  ('SERVICE_MANAGER', 'delete_documents',         true),
  ('OFFICE',          'create_case',              true),
  ('OFFICE',          'complete_professional_step', false),
  ('OFFICE',          'complete_closure_step',    true),
  ('OFFICE',          'manage_settings',          false),
  ('OFFICE',          'decide_approvals',         false),
  ('OFFICE',          'manage_extras_status',     false),
  ('OFFICE',          'upload_documents',         true),
  ('OFFICE',          'delete_documents',         true),
  ('CEO',             'create_case',              true),
  ('CEO',             'complete_professional_step', true),
  ('CEO',             'complete_closure_step',    true),
  ('CEO',             'manage_settings',          true),
  ('CEO',             'decide_approvals',         true),
  ('CEO',             'manage_extras_status',     true),
  ('CEO',             'upload_documents',         true),
  ('CEO',             'delete_documents',         true),
  ('PAINTER',         'create_case',              false),
  ('PAINTER',         'complete_professional_step', false),
  ('PAINTER',         'complete_closure_step',    false),
  ('PAINTER',         'manage_settings',          false),
  ('PAINTER',         'decide_approvals',         false),
  ('PAINTER',         'manage_extras_status',     false),
  ('PAINTER',         'upload_documents',         false),
  ('PAINTER',         'delete_documents',         false),
  ('SERVICE_ADVISOR', 'create_case',              false),
  ('SERVICE_ADVISOR', 'complete_professional_step', false),
  ('SERVICE_ADVISOR', 'complete_closure_step',    false),
  ('SERVICE_ADVISOR', 'manage_settings',          false),
  ('SERVICE_ADVISOR', 'decide_approvals',         false),
  ('SERVICE_ADVISOR', 'manage_extras_status',     false),
  ('SERVICE_ADVISOR', 'upload_documents',         false),
  ('SERVICE_ADVISOR', 'delete_documents',         false)
ON CONFLICT (role, action) DO NOTHING;

-- RLS policies for settings tables (CEO only)
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_step_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "CEO can manage role_permissions"
  ON role_permissions FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'CEO'
    )
  );

CREATE POLICY "All authenticated can read workflow_step_templates"
  ON workflow_step_templates FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "CEO can manage workflow_step_templates"
  ON workflow_step_templates FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'CEO'
    )
  );


-- =============================================================================
-- 010_fix_rls_ceo.sql
-- =============================================================================
-- Migration 010: Fix RLS INSERT policies to allow CEO
-- CEO has branch_id = NULL so the branch_id IN (...) check always fails for CEO

-- Fix cars INSERT: allow CEO to insert into any branch
DROP POLICY IF EXISTS cars_insert ON cars;
CREATE POLICY cars_insert ON cars FOR INSERT TO authenticated
  WITH CHECK (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
  );

-- Fix cars UPDATE: allow CEO to update any car
DROP POLICY IF EXISTS cars_update ON cars;
CREATE POLICY cars_update ON cars FOR UPDATE TO authenticated
  USING (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
  );

-- Fix cases INSERT: allow CEO to insert into any branch
DROP POLICY IF EXISTS cases_insert ON cases;
CREATE POLICY cases_insert ON cases FOR INSERT TO authenticated
  WITH CHECK (
    branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
  );

-- =============================================================================
-- 010_rls_case_workflow_fixes.sql
-- =============================================================================
-- Migration 010: RLS fixes for case creation and workflow step completion
-- 1) Allow inserting case_workflow_runs when the case was just created by the current user
--    (fixes "new row violates row-level security policy for table case_workflow_runs")
-- 2) Allow CEO to update case_workflow_runs and case_workflow_steps (branch_id may be null for CEO)

-- case_workflow_runs: INSERT for case creator (so createCase can add the run after inserting case)
CREATE POLICY case_workflow_runs_insert_creator ON case_workflow_runs
  FOR INSERT TO authenticated
  WITH CHECK (
    case_id IN (SELECT id FROM cases WHERE created_by = auth.uid())
  );

-- case_workflow_runs: UPDATE for CEO (e.g. when completing run)
CREATE POLICY case_workflow_runs_update_ceo ON case_workflow_runs
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO'));

-- case_workflow_steps: UPDATE for CEO (so CEO can complete steps)
CREATE POLICY case_workflow_steps_update_ceo ON case_workflow_steps
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO'));


-- =============================================================================
-- 011_fix_rls_workflow_steps_ceo.sql
-- =============================================================================
-- Migration 011: Fix RLS INSERT policy for case_workflow_steps to allow CEO
-- CEO has branch_id = NULL so the branch_id IN (...) check always fails.
-- The existing case_workflow_steps_insert policy blocks CEO from inserting steps.
-- Solution: add additive policy allowing CEO to insert any workflow step.

DROP POLICY IF EXISTS case_workflow_steps_insert_ceo ON case_workflow_steps;
CREATE POLICY case_workflow_steps_insert_ceo ON case_workflow_steps
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
  );

-- Also allow creator of the case to insert steps (covers SERVICE_MANAGER edge cases)
DROP POLICY IF EXISTS case_workflow_steps_insert_creator ON case_workflow_steps;
CREATE POLICY case_workflow_steps_insert_creator ON case_workflow_steps
  FOR INSERT TO authenticated
  WITH CHECK (
    run_id IN (
      SELECT cwr.id FROM case_workflow_runs cwr
      JOIN cases c ON c.id = cwr.case_id
      WHERE c.created_by = auth.uid()
    )
  );


-- =============================================================================
-- 012_fix_ceo_rls_and_approval_config.sql
-- =============================================================================
-- Migration 012: Fix CEO RLS INSERT policies + add requires_ceo_approval to workflow_step_templates
-- CEO has branch_id = NULL so branch_id IN (...) checks always fail for CEO

-- Fix case_workflow_runs INSERT: CEO needs to create closure workflow runs
DROP POLICY IF EXISTS case_workflow_runs_insert ON case_workflow_runs;
CREATE POLICY case_workflow_runs_insert ON case_workflow_runs FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
    OR case_id IN (SELECT id FROM cases WHERE branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid()))
  );

-- Fix ceo_approvals INSERT: CEO (and service managers) need to insert approvals when completing steps
DROP POLICY IF EXISTS ceo_approvals_insert ON ceo_approvals;
CREATE POLICY ceo_approvals_insert ON ceo_approvals FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
    OR case_id IN (SELECT id FROM cases WHERE branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid()))
  );

-- Add requires_ceo_approval field to workflow_step_templates
ALTER TABLE workflow_step_templates
  ADD COLUMN IF NOT EXISTS requires_ceo_approval BOOLEAN NOT NULL DEFAULT FALSE;

-- Set WAIT_APPRAISER_APPROVAL as requiring CEO approval (matching current hardcoded logic)
UPDATE workflow_step_templates
  SET requires_ceo_approval = TRUE
  WHERE step_key = 'WAIT_APPRAISER_APPROVAL';


-- =============================================================================
-- 013_feature_additions.sql
-- =============================================================================
-- 013: Feature additions based on client feedback
-- Adds: notes, painter_status, sub-fields for ENTER_WORK, QC assignee,
--       estimate_link, case_id on notifications, system_messages table

-- ─── cases table additions ─────────────────────────────────────────────────
ALTER TABLE cases ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS painter_status TEXT DEFAULT 'IN_WORK';
ALTER TABLE cases ADD COLUMN IF NOT EXISTS parts_ordered BOOLEAN;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS parts_arrived BOOLEAN;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS qc_assignee TEXT;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS estimate_link TEXT;

-- ─── notifications: add case_id for deep-linking ──────────────────────────
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS case_id UUID REFERENCES cases(id) ON DELETE SET NULL;

-- ─── system_messages (CEO announcements shown to all users) ───────────────
CREATE TABLE IF NOT EXISTS system_messages (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message    TEXT NOT NULL,
  is_active  BOOLEAN DEFAULT true,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE system_messages ENABLE ROW LEVEL SECURITY;

-- Everyone can read active messages
DROP POLICY IF EXISTS "read_system_messages" ON system_messages;
CREATE POLICY "read_system_messages" ON system_messages
  FOR SELECT USING (is_active = true);

-- Only CEO can insert/update/delete
DROP POLICY IF EXISTS "ceo_manage_system_messages" ON system_messages;
CREATE POLICY "ceo_manage_system_messages" ON system_messages
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO'
    )
  );


-- =============================================================================
-- 014_performance_indexes.sql
-- =============================================================================
-- 014: Performance indexes for common query patterns

-- case_workflow_runs: filtered by case_id + workflow_type + status
CREATE INDEX IF NOT EXISTS idx_workflow_runs_case_type
  ON case_workflow_runs (case_id, workflow_type, status);

-- case_workflow_steps: filtered by run_id (most frequent access)
CREATE INDEX IF NOT EXISTS idx_workflow_steps_run_id
  ON case_workflow_steps (run_id, order_index);

-- cases: filtering open cases by branch
CREATE INDEX IF NOT EXISTS idx_cases_branch_closed
  ON cases (branch_id, closed_at);

-- cases: general_status filter
CREATE INDEX IF NOT EXISTS idx_cases_general_status
  ON cases (general_status) WHERE closed_at IS NULL;

-- notifications: user feed query
CREATE INDEX IF NOT EXISTS idx_notifications_user_created
  ON notifications (user_id, created_at DESC);

-- notifications: unread count
CREATE INDEX IF NOT EXISTS idx_notifications_user_read
  ON notifications (user_id, read) WHERE read = false;

-- ceo_approvals: by case
CREATE INDEX IF NOT EXISTS idx_ceo_approvals_case_id
  ON ceo_approvals (case_id, status);

-- bodywork_extras: blocking check
CREATE INDEX IF NOT EXISTS idx_bodywork_extras_case_status
  ON bodywork_extras (case_id, status);

-- audit_events: entity lookup
CREATE INDEX IF NOT EXISTS idx_audit_events_entity
  ON audit_events (entity_type, entity_id, created_at DESC);


-- =============================================================================
-- 015_closure_checklist_state.sql
-- =============================================================================
-- Add persistent storage for Ilana's closure checklist per case
ALTER TABLE cases ADD COLUMN IF NOT EXISTS closure_checklist_state JSONB DEFAULT '{}' NOT NULL;

-- Comment explaining format: {"0": true, "2": true} — keys are item indices, value is always true (absent = false)
COMMENT ON COLUMN cases.closure_checklist_state IS 'Stores checked state of closure checklist items. Keys are item indices (0-based strings), value is true when checked.';


-- =============================================================================
-- 016_appraiser_status.sql
-- =============================================================================
-- 016: Appraiser status column on cases
-- Values: APPROVED | NOT_APPROVED | WAITING_SETTLEMENT

ALTER TABLE cases ADD COLUMN IF NOT EXISTS appraiser_status TEXT;


-- =============================================================================
-- 017_soft_delete_and_painter.sql
-- =============================================================================
-- 017: Soft delete on cases, bodywork advisor flag, painter requests + images,
--      document_type on case_documents. Storage bucket `painter-images` must
--      be created in Supabase Dashboard BEFORE running this migration.

-- ─── Soft delete on cases ────────────────────────────────────────────────
ALTER TABLE cases ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS deleted_by UUID REFERENCES profiles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_cases_deleted_at ON cases(deleted_at) WHERE deleted_at IS NULL;

-- ─── Bodywork advisor flag on profiles ───────────────────────────────────
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_bodywork_advisor BOOLEAN DEFAULT false;

-- Seed: SERVICE_MANAGER + SERVICE_ADVISOR default to bodywork advisors
UPDATE profiles
   SET is_bodywork_advisor = true
 WHERE role IN ('SERVICE_MANAGER', 'SERVICE_ADVISOR')
   AND is_bodywork_advisor IS DISTINCT FROM true;

-- ─── Painter requests ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS painter_requests (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id       UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  description   TEXT NOT NULL,
  request_type  TEXT NOT NULL CHECK (request_type IN ('WORK', 'PARTS')),
  status        TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'DONE')),
  created_by    UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_painter_requests_case ON painter_requests(case_id);

ALTER TABLE painter_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS painter_requests_select ON painter_requests;
CREATE POLICY painter_requests_select ON painter_requests
  FOR SELECT TO authenticated
  USING (
    case_id IN (
      SELECT c.id FROM cases c
       WHERE c.branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    )
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
  );

DROP POLICY IF EXISTS painter_requests_insert ON painter_requests;
CREATE POLICY painter_requests_insert ON painter_requests
  FOR INSERT TO authenticated
  WITH CHECK (
    created_by = auth.uid()
    AND case_id IN (
      SELECT c.id FROM cases c
       WHERE c.branch_id IN (SELECT branch_id FROM profiles WHERE id = auth.uid())
    )
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
  );

DROP POLICY IF EXISTS painter_requests_update ON painter_requests;
CREATE POLICY painter_requests_update ON painter_requests
  FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
       WHERE id = auth.uid() AND role IN ('SERVICE_MANAGER', 'CEO')
    )
  );

-- ─── Painter request images ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS painter_request_images (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id  UUID NOT NULL REFERENCES painter_requests(id) ON DELETE CASCADE,
  image_path  TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_painter_request_images_req ON painter_request_images(request_id);

ALTER TABLE painter_request_images ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS painter_request_images_select ON painter_request_images;
CREATE POLICY painter_request_images_select ON painter_request_images
  FOR SELECT TO authenticated
  USING (
    request_id IN (SELECT id FROM painter_requests)
  );

DROP POLICY IF EXISTS painter_request_images_insert ON painter_request_images;
CREATE POLICY painter_request_images_insert ON painter_request_images
  FOR INSERT TO authenticated
  WITH CHECK (
    request_id IN (SELECT id FROM painter_requests WHERE created_by = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'CEO')
  );

-- ─── Storage policies for painter-images bucket ──────────────────────────
-- The bucket itself must be created via Supabase Dashboard → Storage (private).
DROP POLICY IF EXISTS "painter-images authenticated upload" ON storage.objects;
CREATE POLICY "painter-images authenticated upload"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'painter-images');

DROP POLICY IF EXISTS "painter-images authenticated read" ON storage.objects;
CREATE POLICY "painter-images authenticated read"
  ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'painter-images');

-- ─── Document type on case_documents ─────────────────────────────────────
ALTER TABLE case_documents ADD COLUMN IF NOT EXISTS document_type TEXT;


-- =============================================================================
-- 018_fix_rls_recursion.sql
-- =============================================================================
-- 018: Fix infinite recursion in RLS policies on profiles
--
-- Original issue: profiles_select_branch used a subquery on profiles itself,
-- which triggered RLS evaluation on the subquery, which tried
-- profiles_select_branch again → infinite recursion.
--
-- Fix: wrap the profile lookup in SECURITY DEFINER helper functions so RLS is
-- bypassed inside them, then use those helpers in policies instead of subqueries.

CREATE OR REPLACE FUNCTION public.current_user_branch_id()
RETURNS UUID LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT branch_id FROM public.profiles WHERE id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS TEXT LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT role::text FROM public.profiles WHERE id = auth.uid();
$$;

GRANT EXECUTE ON FUNCTION public.current_user_branch_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_user_role() TO authenticated;

-- profiles
DROP POLICY IF EXISTS profiles_select_branch ON profiles;
CREATE POLICY profiles_select_branch ON profiles
  FOR SELECT TO authenticated
  USING (branch_id = public.current_user_branch_id());

-- cars
DROP POLICY IF EXISTS cars_select ON cars;
CREATE POLICY cars_select ON cars
  FOR SELECT TO authenticated
  USING (branch_id = public.current_user_branch_id() OR public.current_user_role() = 'CEO');

DROP POLICY IF EXISTS cars_insert ON cars;
CREATE POLICY cars_insert ON cars
  FOR INSERT TO authenticated
  WITH CHECK (branch_id = public.current_user_branch_id() OR public.current_user_role() = 'CEO');

DROP POLICY IF EXISTS cars_update ON cars;
CREATE POLICY cars_update ON cars
  FOR UPDATE TO authenticated
  USING (branch_id = public.current_user_branch_id() OR public.current_user_role() = 'CEO');

DROP POLICY IF EXISTS cars_select_ceo ON cars;

-- cases
DROP POLICY IF EXISTS cases_select ON cases;
CREATE POLICY cases_select ON cases
  FOR SELECT TO authenticated
  USING (branch_id = public.current_user_branch_id() OR public.current_user_role() = 'CEO');

DROP POLICY IF EXISTS cases_select_ceo ON cases;

DROP POLICY IF EXISTS cases_insert ON cases;
CREATE POLICY cases_insert ON cases
  FOR INSERT TO authenticated
  WITH CHECK (branch_id = public.current_user_branch_id() OR public.current_user_role() = 'CEO');

DROP POLICY IF EXISTS cases_update ON cases;
CREATE POLICY cases_update ON cases
  FOR UPDATE TO authenticated
  USING (branch_id = public.current_user_branch_id() OR public.current_user_role() = 'CEO');

-- case_workflow_runs
DROP POLICY IF EXISTS case_workflow_runs_select ON case_workflow_runs;
CREATE POLICY case_workflow_runs_select ON case_workflow_runs
  FOR SELECT TO authenticated
  USING (
    case_id IN (SELECT id FROM cases WHERE branch_id = public.current_user_branch_id())
    OR public.current_user_role() = 'CEO'
  );

DROP POLICY IF EXISTS case_workflow_runs_select_ceo ON case_workflow_runs;

-- case_workflow_steps
DROP POLICY IF EXISTS case_workflow_steps_select ON case_workflow_steps;
CREATE POLICY case_workflow_steps_select ON case_workflow_steps
  FOR SELECT TO authenticated
  USING (
    run_id IN (
      SELECT cwr.id FROM case_workflow_runs cwr
      JOIN cases c ON c.id = cwr.case_id
      WHERE c.branch_id = public.current_user_branch_id()
    )
    OR public.current_user_role() = 'CEO'
  );

DROP POLICY IF EXISTS case_workflow_steps_select_ceo ON case_workflow_steps;

-- ceo_approvals
DROP POLICY IF EXISTS ceo_approvals_select ON ceo_approvals;
CREATE POLICY ceo_approvals_select ON ceo_approvals
  FOR SELECT TO authenticated
  USING (
    case_id IN (SELECT id FROM cases WHERE branch_id = public.current_user_branch_id())
    OR public.current_user_role() = 'CEO'
  );

DROP POLICY IF EXISTS ceo_approvals_select_ceo ON ceo_approvals;

-- bodywork_extras
DROP POLICY IF EXISTS bodywork_extras_select ON bodywork_extras;
CREATE POLICY bodywork_extras_select ON bodywork_extras
  FOR SELECT TO authenticated
  USING (
    case_id IN (SELECT id FROM cases WHERE branch_id = public.current_user_branch_id())
    OR public.current_user_role() = 'CEO'
  );

DROP POLICY IF EXISTS bodywork_extras_select_ceo ON bodywork_extras;

-- audit_events
DROP POLICY IF EXISTS audit_events_select_ceo ON audit_events;


-- =============================================================================
-- 019_ceo_bypass_profiles_audit.sql
-- =============================================================================
-- 019: Restore CEO bypass for profiles + audit_events that 018 dropped by mistake.

-- CEO can see all profiles (needed for case detail user-name resolution, settings)
DROP POLICY IF EXISTS profiles_select_ceo ON profiles;
CREATE POLICY profiles_select_ceo ON profiles
  FOR SELECT TO authenticated
  USING (public.current_user_role() = 'CEO');

-- CEO can see all audit events
DROP POLICY IF EXISTS audit_events_select_ceo ON audit_events;
CREATE POLICY audit_events_select_ceo ON audit_events
  FOR SELECT TO authenticated
  USING (public.current_user_role() = 'CEO');

